[project]
name = "rabindra-scraper"
version = "0.1.0"
description = "Scraper for poems from Rabindra Rachanabali website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "parsel>=1.10.0",
    "requests>=2.32.5",
]
